baseURL = "http://lisemoxolll.dk/kea/portfolio"
languageCode = "en-us"
title = "Home"
theme = "Ananke"




[[menu.main]]
name               	= "Om"
weight             	= 2
identifier         	= "om"
url                	= "/om/"

[[menu.main]]
name               	= "Kontakt"
weight             	= 3
identifier         	= "kontakt"
url                	= "/kontakt/"

[[menu.main]]
name               	= "Portfolio"
weight             	= 5
identifier         	= "portfolio"
url                	= "/portfolio/"


