baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"


[[menu.main]]
name               	= "Home"
weight             	= 1
identifier         	= "home"
url                	= "/"

[[menu.main]]
name               	= "Om"
weight             	= 2
identifier         	= "om"
url                	= "/om/"

[[menu.main]]
name               	= "Kontakt"
weight             	= 3
identifier         	= "kontakt"
url                	= "/kontakt/"

[[menu.main]]
name               	= "Blog"
weight             	= 4
identifier         	= "blog"
url                	= "/blog/"

[[menu.main]]
name               	= "Portfolio"
weight             	= 5
identifier         	= "portfolio"
url                	= "/portfolio/"


